# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-02 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpayment',
            old_name='dafault_credit_card_number',
            new_name='default_credit_card_number',
        ),
    ]
