# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-02 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200802_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dafault_credit_card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('default_cvv', models.CharField(blank=True, max_length=20, null=True)),
                ('default_expiry_month', models.CharField(blank=True, max_length=40, null=True)),
                ('default_expiry_year', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
