# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-16 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200802_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpayment',
            old_name='default_expiry_month',
            new_name='default_country',
        ),
        migrations.RenameField(
            model_name='userpayment',
            old_name='default_credit_card_number',
            new_name='default_phone_number',
        ),
        migrations.RenameField(
            model_name='userpayment',
            old_name='default_cvv',
            new_name='default_postcode',
        ),
        migrations.RenameField(
            model_name='userpayment',
            old_name='default_expiry_year',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='userpayment',
            name='default_county',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='default_street_address1',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='default_street_address2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='default_town_or_city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
