# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-17 18:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20200816_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayment',
            name='user',
        ),
        migrations.AddField(
            model_name='userpayment',
            name='creator_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
