# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-17 18:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_auto_20200817_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFootball',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(blank=True, max_length=20, null=True)),
                ('favorite_player', models.CharField(blank=True, max_length=200, null=True)),
                ('favorite_shirts', models.CharField(blank=True, max_length=200, null=True)),
                ('shield', models.ImageField(upload_to='badge')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserPayment',
        ),
    ]
