# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-17 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200817_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfootball',
            name='shield',
            field=models.ImageField(blank=True, upload_to='shields'),
        ),
    ]
