# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-19 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200819_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfootball',
            name='size',
            field=models.CharField(blank=True, choices=[('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('Extra Large', 'XL')], default='Medium', max_length=12),
        ),
    ]
